- I got autoconf so now I can fix up the configuration options.  Added   cpu-level 6, as the default. - added --enable-processors=N.  it warns you unless you use 1, 2, or 4. - added --enable-apic.  warns you if apic is off but processors>1. - if debugger selected, it warns you to turn on disasm too

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -21,58 +21,12 @@ AC_CHECK_SIZEOF(unsigned short)
 AC_CHECK_SIZEOF(unsigned int)
 AC_CHECK_SIZEOF(unsigned long)
 AC_CHECK_SIZEOF(unsigned long long)
-AC_CHECK_SIZEOF(int *)
 AC_CHECK_FUNCS(select, AC_DEFINE(BX_HAVE_SELECT))
-AC_CHECK_FUNCS(snprintf, AC_DEFINE(BX_HAVE_SNPRINTF))
-AC_CHECK_FUNCS(strtoull, AC_DEFINE(BX_HAVE_STRTOULL))
-AC_CHECK_FUNCS(strdup, AC_DEFINE(BX_HAVE_STRDUP))
 
-AC_MSG_CHECKING(if compiler allows empty structs)
-AC_TRY_COMPILE([], [typedef struct { } junk;], 
-    AC_MSG_RESULT(yes),
-    [
-      AC_DEFINE(BX_NO_EMPTY_STRUCTS)
-      AC_MSG_RESULT(no)
-    ])
-
-AC_MSG_CHECKING(if compiler allows __attribute__)
-AC_TRY_COMPILE([], [typedef struct { } __attribute__ ((packed)) junk;], 
-    AC_MSG_RESULT(yes),
-    [
-      AC_MSG_RESULT(no)
-      AC_DEFINE(BX_NO_ATTRIBUTES)
-    ])
-
-AC_LANG_SAVE
-AC_LANG_CPLUSPLUS
-AC_MSG_CHECKING(for hash_map.h)
-AC_TRY_COMPILE([#include <hash_map.h>], [],
-   [
-     AC_MSG_RESULT(yes)
-     AC_DEFINE(BX_HAVE_HASH_MAP)
-   ], AC_MSG_RESULT(no))
-
-AC_MSG_CHECKING(if compiler allows blank labels)
-AC_TRY_COMPILE([], [ { label1: } ],
-    AC_MSG_RESULT(yes),
-    [
-      AC_MSG_RESULT(no)
-      AC_DEFINE(BX_NO_BLANK_LABELS)
-    ])
-AC_LANG_RESTORE
-
-AC_MSG_CHECKING(if compiler allows LL for 64-bit constants)
-AC_TRY_COMPILE([], [ { 42LL; } ],
-    AC_MSG_RESULT(yes),
-    [
-      AC_MSG_RESULT(no)
-      AC_DEFINE(BX_64BIT_CONSTANTS_USE_LL, 0)
-    ])
-AC_LANG_RESTORE
 
 AC_MSG_CHECKING(for cpu level)
 AC_ARG_ENABLE(cpu-level,
-  [  --enable-cpu-level                select cpu level (3,4,5)],
+  [  --enable-cpu-level                select cpu level (3,4,5,6)],
   [case "$enableval" in
      3)
        AC_MSG_RESULT(3)
@@ -89,6 +43,11 @@ AC_ARG_ENABLE(cpu-level,
        AC_DEFINE(BX_CPU_LEVEL, 5)
        AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
        ;;
+     6)
+       AC_MSG_RESULT(6)
+       AC_DEFINE(BX_CPU_LEVEL, 6)
+       AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
+       ;;
      *)
        echo " "
        echo "ERROR: you must supply a valid CPU level to --enable-cpu-level"
@@ -97,9 +56,47 @@ AC_ARG_ENABLE(cpu-level,
    esac
   ],
   [
-   AC_MSG_RESULT(5)
-   AC_DEFINE(BX_CPU_LEVEL, 5)
-   AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
+   AC_MSG_RESULT(6)
+   AC_DEFINE(BX_CPU_LEVEL, 6)
+   AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
+  ]
+  )
+
+AC_MSG_CHECKING(for number of processors)
+AC_ARG_ENABLE(processors,
+  [  --enable-processors                select number of processors (1,2,4)],
+  [case "$enableval" in
+     1)
+       AC_MSG_RESULT(1)
+       AC_DEFINE(BX_SMP_PROCESSORS, 1)
+       AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 0)
+       AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 1)
+       ;;
+     2)
+       AC_MSG_RESULT(2)
+       AC_DEFINE(BX_SMP_PROCESSORS, 2)
+       AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 0)
+       AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 2)
+       ;;
+     4)
+       AC_MSG_RESULT(4)
+       AC_DEFINE(BX_SMP_PROCESSORS, 4)
+       AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 2)
+       AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 4)
+       ;;
+     *)
+       echo " "
+       echo "WARNING: processors != [1,2,4] can work, but you need to modify rombios.c manually"
+       ;;
+   esac
+   bx_procs="$enableval"
+  ],
+  [
+   AC_MSG_RESULT(2)
+   AC_DEFINE(BX_SMP_PROCESSORS, 2)
+   AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 0)
+   AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 2)
+   bx_procs=2
   ]
   )
 
@@ -156,6 +153,43 @@ AC_ARG_ENABLE(dynamic,
 AC_SUBST(DYNAMIC_VAR)
 AC_SUBST(AS_DYNAMIC_OBJS)
 AC_SUBST(AS_DYNAMIC_INCS)
+
+AC_MSG_CHECKING(for APIC support)
+AC_ARG_ENABLE(apic,
+  [  --enable-apic                   enable APIC support],
+  [if test "$enableval" = yes; then
+    AC_MSG_RESULT(yes)
+    AC_DEFINE(BX_APIC_SUPPORT, 1)
+    IOAPIC_OBJS='ioapic.o'
+    APIC_OBJS='apic.o'
+   else
+    AC_MSG_RESULT(no)
+    if test "$bx_procs" -gt 1; then
+      echo "Number of processors = $bx_procs"
+      echo "ERROR: With processors > 1 you must use --enable-apic"
+      exit 1
+    fi
+    AC_DEFINE(BX_APIC_SUPPORT, 0)
+    IOAPIC_OBJS=''
+    APIC_OBJS=''
+   fi
+   ],
+  [
+    if test "$bx_procs" -gt 1; then
+      AC_MSG_RESULT(yes)
+      AC_DEFINE(BX_APIC_SUPPORT, 1)
+      IOAPIC_OBJS='ioapic.o'
+      APIC_OBJS='apic.o'
+    else
+      AC_MSG_RESULT(no)
+      AC_DEFINE(BX_APIC_SUPPORT, 0)
+      IOAPIC_OBJS=''
+      APIC_OBJS=''
+     fi
+   ]
+  )
+AC_SUBST(IOAPIC_OBJS)
+AC_SUBST(APIC_OBJS)
 
 AC_MSG_CHECKING(for NE2000 support)
 AC_ARG_ENABLE(ne2000,
@@ -276,6 +310,18 @@ AC_ARG_ENABLE(debugger,
     ]
   )
 AC_SUBST(DEBUGGER_VAR)
+
+AC_CHECK_LIB(readline, 
+  readline,
+  [
+    READLINE_LIB='-lreadline'
+  ]
+)
+  AC_SUBST(READLINE_LIB)
+
+AC_CHECK_HEADER(readline/history.h,
+  AC_DEFINE(HAVE_READLINE_HISTORY_H)
+  )
 
 AC_MSG_CHECKING(for disassembler support)
 AC_ARG_ENABLE(disasm,
@@ -665,14 +711,8 @@ elif test "$with_win32_vcpp" = yes; then
   COMMAND_SEPARATOR=""
   CD_UP_ONE="cd .."
   CD_UP_TWO="cd ..\.."
-  AC_DEFINE(BX_64BIT_CONSTANTS_USE_LL, 0)
-  AC_DEFINE(inline, __inline)
-  AC_DEFINE(BX_NO_EMPTY_STRUCTS, 1)
-  AC_DEFINE(BX_NO_ATTRIBUTES, 1)
-  AC_DEFINE(BX_HAVE_HASH_MAP, 0)
 elif test "$with_macos" = yes; then
   AC_DEFINE(BX_WITH_MACOS, 1)
-  AC_DEFINE(BX_HAVE_STRDUP, 0)
   GUI_OBJS='$(GUI_OBJS_MACOS)'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_MACOS)'
 else
@@ -696,6 +736,8 @@ AC_SUBST(COMMAND_SEPARATOR)
 AC_SUBST(CD_UP_ONE)
 AC_SUBST(CD_UP_TWO)
 
+AC_PATH_PROG(GZIP, gzip)
+AC_PATH_PROG(TAR, tar)
 
 AC_OUTPUT(Makefile iodev/Makefile debug/Makefile bios/Makefile \
          cpu/Makefile memory/Makefile gui/Makefile disasm/Makefile \
