20021020 -preTora merge against 20021019 HEAD plus compile fixes, possible changes in timer semantics.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -2,7 +2,7 @@ dnl // Process this file with autoconf to produce a configure script.
 
 AC_PREREQ(2.50)
 AC_INIT(bochs.h)
-AC_REVISION([[$Id: configure.in,v 1.135 2002/09/27 20:06:57 bdenney Exp $]])
+AC_REVISION([[$Id: configure.in,v 1.135.2.1 2002/10/20 22:25:59 zwane Exp $]])
 AC_CONFIG_HEADER(config.h)
 
 dnl // Put Bochs version information right here so that it gets substituted
@@ -71,8 +71,10 @@ case "$target" in
     DEFAULT_GUI=x11
     ;;
 esac
-CFLAGS="$CFLAGS $ADD_FLAGS"
-CXXFLAGS="$CXXFLAGS $ADD_FLAGS"
+if test "${ADD_FLAGS:+set}" = set; then
+      CFLAGS="$CFLAGS $ADD_FLAGS"
+      CXXFLAGS="$CXXFLAGS $ADD_FLAGS"
+fi
 
 AC_MSG_CHECKING(for standard CFLAGS on this platform)
 AC_MSG_RESULT($ADD_FLAGS)
@@ -123,6 +125,34 @@ AC_CHECK_FUNCS(abort, AC_DEFINE(BX_HAVE_ABORT))
 AC_CHECK_FUNCS(gettimeofday, AC_DEFINE(BX_HAVE_GETTIMEOFDAY))
 AC_CHECK_TYPE(socklen_t, AC_DEFINE(BX_HAVE_SOCKLEN_T), , [#include <sys/types.h>
 #include <sys/socket.h>])
+
+dnl As of autoconf 2.53, the standard largefile test fails for Linux/gcc.
+dnl It does not put the largefiles arguments into CFLAGS, even though Linux/gcc
+dnl does need them.  Since wxWindows had already solved this exact problem,
+dnl Bryce asked Vadim Zeitlin of the wxWindows project if Bochs could grab
+dnl their largefile test, and he said it was fine.  The re-implemented
+dnl AC_SYS_LARGEFILE test can be found in aclocal.m4.
+AC_SYS_LARGEFILE
+
+dnl This logic came from wxWindows as well.  Bryce added the CFLAGS and 
+dnl CXXFLAGS lines, since Bochs makefiles don't use CPPFLAGS at all.
+dnl
+dnl we need to define _FILE_OFFSET_BITS or _LARGE_FILES on the compiler command
+dnl line because otherwise the system headers risk being included before
+dnl config.h which defines these constants leading to inconsistent
+dnl sizeof(off_t) in different source files of the same program and linking
+dnl problems
+if test "x$wx_largefile" = "xyes"; then
+    if test "x$ac_cv_sys_file_offset_bits" = "x64"; then
+        BX_LARGEFILE_FLAGS="-D_FILE_OFFSET_BITS=64 -D_LARGE_FILES"
+    else 
+        BX_LARGEFILE_FLAGS="-D_LARGE_FILES"
+    fi
+    CPPFLAGS="$CPPFLAGS $BX_LARGEFILE_FLAGS"
+    CFLAGS="$CFLAGS $BX_LARGEFILE_FLAGS"
+    CXXFLAGS="$CXXFLAGS $BX_LARGEFILE_FLAGS"
+fi
+dnl ---end of largefile tests
 
 AC_MSG_CHECKING(for struct timeval)
 AC_TRY_COMPILE([#include <sys/time.h>],
@@ -605,14 +635,14 @@ AC_ARG_ENABLE(guest2host-tlb,
   [  --enable-guest2host-tlb           support guest to host addr TLB for speed],
   [if test "$enableval" = yes; then
     AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SupportGuest2HostTLB, 1)
+    speedup_guest2host_tlb=1
    else
     AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SupportGuest2HostTLB, 0)
+    speedup_guest2host_tlb=0
    fi],
   [
     AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SupportGuest2HostTLB, 0)
+    speedup_guest2host_tlb=0
     ]
   )
 
@@ -621,14 +651,14 @@ AC_ARG_ENABLE(repeat-speedups,
   [  --enable-repeat-speedups          support repeated IO and mem copy speedups],
   [if test "$enableval" = yes; then
     AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SupportRepeatSpeedups, 1)
+    speedup_repeat=1
    else
     AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SupportRepeatSpeedups, 0)
+    speedup_repeat=0
    fi],
   [
     AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SupportRepeatSpeedups, 0)
+    speedup_repeat=0
     ]
   )
 
@@ -637,14 +667,14 @@ AC_ARG_ENABLE(icache,
   [  --enable-icache                   support instruction cache (runs faster)],
   [if test "$enableval" = yes; then
     AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SupportICache, 1)
+    speedup_iCache=1
    else
     AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SupportICache, 0)
+    speedup_iCache=0
    fi],
   [
     AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SupportICache, 0)
+    speedup_iCache=0
     ]
   )
 
@@ -675,14 +705,14 @@ AC_ARG_ENABLE(host-specific-asms,
   [  --enable-host-specific-asms       support for host specific inline assembly],
   [if test "$enableval" = yes; then
     AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SupportHostAsms, 1)
+    speedup_host_specific_asms=1
    else
     AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SupportHostAsms, 0)
+    speedup_host_specific_asms=0
    fi],
   [
     AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SupportHostAsms, 1)
+    speedup_host_specific_asms=1
     ]
   )
 
@@ -832,6 +862,62 @@ AC_ARG_ENABLE(disasm,
     ]
   )
 AC_SUBST(DISASM_VAR)
+
+AC_MSG_CHECKING(for ALL optimizations enabled)
+AC_ARG_ENABLE(all-optimizations,
+  [  --enable-all-optimizations        compile in all possible optimizations],
+  [if test "$enableval" = yes; then
+    AC_MSG_RESULT(yes)
+    speedups_all=1
+   else
+    AC_MSG_RESULT(no)
+    speedups_all=0
+   fi
+   ],
+  [
+    AC_MSG_RESULT(no)
+    speedups_all=0
+    ]
+  )
+
+#
+# Optimizations section.  Decide what the status of various optimizations
+# should be based on configure choices and other factors.
+#
+
+if test "$speedups_all" = 1; then
+  # Configure requested to force all options enabled.
+  speedup_guest2host_tlb=1
+  speedup_repeat=1
+  speedup_iCache=1
+  speedup_host_specific_asms=1
+fi
+
+if test "$speedup_guest2host_tlb" = 1; then
+  AC_DEFINE(BX_SupportGuest2HostTLB, 1)
+else
+  AC_DEFINE(BX_SupportGuest2HostTLB, 0)
+fi
+
+if test "$speedup_repeat" = 1; then
+  AC_DEFINE(BX_SupportRepeatSpeedups, 1)
+else
+  AC_DEFINE(BX_SupportRepeatSpeedups, 0)
+fi
+
+if test "$speedup_iCache" = 1; then
+  AC_DEFINE(BX_SupportICache, 1)
+else
+  AC_DEFINE(BX_SupportICache, 0)
+fi
+
+if test "$speedup_host_specific_asms" = 1; then
+  AC_DEFINE(BX_SupportHostAsms, 1)
+else
+  AC_DEFINE(BX_SupportHostAsms, 0)
+fi
+
+
 
 READLINE_LIB=""
 rl_without_curses_ok=no
@@ -1062,7 +1148,44 @@ AC_ARG_ENABLE(fpu,
 AC_SUBST(FPU_VAR)
 AC_SUBST(FPU_GLUE_OBJ)
 
+support_sse=0
+AC_MSG_CHECKING(for SSE support)
+AC_ARG_ENABLE(sse,
+  [  --enable-sse                      SSE/SSE2 support (--enable-sse=[no|1|2])],
+  [case "$enableval" in
+    no | 0)
+      support_sse=0
+      AC_MSG_RESULT(no)
+      ;;
+    yes | 1)
+      support_sse=1
+      AC_MSG_RESULT(SSE only)
+      ;;
+    2)
+      support_sse=2
+      AC_MSG_RESULT(SSE and SSE2)
+      ;;
+    *)
+      echo "ERROR: --enable-sse=$enableval not understood. Use --enable-sse=[no|1|2]"
+      exit 1
+      ;;
+   esac
+   ],
+  [
+    AC_MSG_RESULT(no)
+  ]
+  )
 
+if test "$support_sse" = 2; then
+  AC_DEFINE(BX_SUPPORT_SSE,  1)
+  AC_DEFINE(BX_SUPPORT_SSE2, 1)
+elif test "$support_sse" = 1; then
+  AC_DEFINE(BX_SUPPORT_SSE,  1)
+  AC_DEFINE(BX_SUPPORT_SSE2, 0)
+else
+  AC_DEFINE(BX_SUPPORT_SSE,  0)
+  AC_DEFINE(BX_SUPPORT_SSE2, 0)
+fi
 
 AC_MSG_CHECKING(for x86 debugger support)
 AC_ARG_ENABLE(x86-debugger,
@@ -1105,10 +1228,12 @@ AC_ARG_ENABLE(cdrom,
       AC_MSG_RESULT(Using OSX IOKit CD Interface)	
       CDROM_OBJS="cdrom_osx.o"
       EXTRA_LINK_OPTS="${EXTRA_LINK_OPTS} -framework IOKit -framework CoreFoundation"
-    elif test "$with_beos" = yes; then
-      # use the beos cdrom file instead
-      CDROM_OBJS="$CDROM_OBJS cdrom_beos.o"
     fi
+    case $target in
+      *-beos*)
+	# use the beos cdrom file instead
+	CDROM_OBJS="$CDROM_OBJS cdrom_beos.o"
+    esac
     AC_DEFINE(BX_SUPPORT_CDROM, 1)
    fi],
   [
@@ -1156,6 +1281,7 @@ AC_ARG_ENABLE(sb16,
          SB16_OBJS='$(SB16_WIN_OBJS)'
          AC_DEFINE(BX_SOUND_OUTPUT_C, bx_sound_windows_c)
          AC_MSG_RESULT(win)
+		 DEVICE_LINK_OPTS="$DEVICE_LINK_OPTS -lwinmm"
          ;;
        *)
          echo " "
@@ -1175,8 +1301,32 @@ AC_ARG_ENABLE(sb16,
 AC_SUBST(SB16_OBJS)
 
 
+AC_MSG_CHECKING(for gdb stub enable)
+AC_ARG_ENABLE(gdb-stub,
+  [  --enable-gdb-stub                 enable gdb stub support],
+  [if test "$enableval" = yes; then
+    AC_MSG_RESULT(yes)
+    AC_DEFINE(BX_GDBSTUB, 1)
+    GDBSTUB_VAR='$(GDBSTUB_OBJS)'
+    if test "$bx_debugger" = 1; then
+      AC_MSG_ERROR(--enable-debugger and --enable-gdb-stub are mutually exclusive)
+    fi
+   else
+    AC_MSG_RESULT(no)
+    AC_DEFINE(BX_GDBSTUB, 0)
+    GDBSTUB_VAR=''
+   fi],
+  [
+    AC_MSG_RESULT(no)
+    AC_DEFINE(BX_GDBSTUB, 0)
+    GDBSTUB_VAR=''
+    ]
+  )
+AC_SUBST(GDBSTUB_VAR)
+
+
 AC_ARG_ENABLE(hga-dumps,
-  [  --enable-hga-dumps=Nmicroseconds  copy memory to HGA video buffer every N useconds],
+  [  --enable-hga-dumps=Nmicroseconds  copy memory to HGA buffer every N usec],
   AC_DEFINE_UNQUOTED(BX_EMULATE_HGA_DUMPS, $enableval),
   )
 
@@ -1216,6 +1366,7 @@ AC_DEFINE(BX_PROVIDE_CPU_MEMORY, 1)
 NONINLINE_VAR='$(NONINLINE_OBJS)'
 
 AC_SUBST(IODEV_LIB_VAR)
+AC_SUBST(EXTRA_BX_OBJS)
 AC_SUBST(NONINLINE_VAR)
 AC_SUBST(INLINE_VAR)
 AC_SUBST(EXTERNAL_DEPENDENCY)
@@ -1286,6 +1437,7 @@ OFP="-o "
 MAKELIB="ar rv \$@"
 RMCOMMAND="rm -f "
 LINK="\$(CXX) -o \$@ \$(CXXFLAGS)"
+LINK_CONSOLE="\$(CXX) -o \$@ \$(CXXFLAGS_CONSOLE)"
 EXE=""
 COMMAND_SEPARATOR="&& \\"
 CD_UP_ONE="echo done"
@@ -1296,7 +1448,12 @@ INSTALL_LIST_FOR_PLATFORM=
 
 # check for existence of and usable version of wxWindows.  This comes
 # early so that it could affect which one gets chosen.
-AC_CHECK_PROG(WX_CONFIG, [ wx-config --version ], wx-config, not_found)
+if test x$WX_CONFIG = x; then
+  AC_CHECK_PROG(WX_CONFIG, [ wx-config --version ], wx-config, not_found)
+fi
+AC_MSG_CHECKING(for wxWindows configuration script)
+AC_MSG_RESULT($WX_CONFIG)
+  
 ok_wx_version=0
 AC_MSG_CHECKING(for wxWindows library version)
 if test x$WX_CONFIG != xnot_found; then
@@ -1341,7 +1498,10 @@ elif test "$with_beos" = yes; then
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_BEOS)'
 elif test "$with_sdl" = yes; then
   AC_MSG_RESULT(sdl)
-  CFLAGS="$CFLAGS \`sdl-config --cflags\`"
+  # GUI_*FLAGS are added to the compilation of every bochs file, not just
+  # the files in gui/*.cc.
+  GUI_CFLAGS="$CFLAGS \`sdl-config --cflags\`"
+  GUI_CXXFLAGS="$CXXFLAGS \`sdl-config --cflags\`"
   AC_DEFINE(BX_WITH_SDL, 1)
   GUI_OBJS='$(GUI_OBJS_SDL) control.o'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_SDL)'
@@ -1408,20 +1568,21 @@ elif test "$with_wx" = yes; then
     WX_CFLAGS="$WX_CFLAGS \`gtk-config --cflags\`"
     WX_CXXFLAGS="$WX_CXXFLAGS \`gtk-config --cflags\`"
   fi
+  # GUI_*FLAGS are added to the compilation of every bochs file, not just
+  # the files in gui/*.cc.
+  GUI_CFLAGS="$CFLAGS $WX_CFLAGS"
+  GUI_CXXFLAGS="$CXXFLAGS $WX_CXXFLAGS"
   # wxwindows is the only one without control.o in GUI_OBJS
-  CFLAGS="$CFLAGS $WX_CFLAGS"
-  CXXFLAGS="$CXXFLAGS $WX_CXXFLAGS"
   GUI_OBJS='$(GUI_OBJS_WX)'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_WX)'
   # using debugger with readline is failing due to thread/signal handler
   # problems.
-  if test "$use_readline" = 1 -a "$bx_debugger" = 1; then
-    echo ERROR: You have selected wxWindows, the debugger, and the readline 
-    echo library.  This combination is known to trigger problems with SIGINT 
-    echo handling.  Please run configure again with --disable-readline to 
-    echo correct this.
-    exit 1
-  fi
+  case $target in
+    *-pc-windows* | *-cygwin* | *-mingw32*)
+       EXTRA_BX_OBJS="$EXTRA_BX_OBJS wxbochs_resources.o"
+	   GUI_LINK_OPTS_WX="$GUI_LINK_OPTS_WX --subsystem,windows -mwindows"
+       ;;
+  esac
 else
   AC_MSG_RESULT(none)
   AC_DEFINE(BX_WITH_NOGUI, 1)
@@ -1429,6 +1590,9 @@ else
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_NOGUI)'
 fi
 
+AC_SUBST(GUI_CFLAGS)
+AC_SUBST(GUI_CXXFLAGS)
+AC_SUBST(WX_CONFIG)
 AC_SUBST(WX_CFLAGS)
 AC_SUBST(WX_CXXFLAGS)
 
@@ -1456,6 +1620,7 @@ case "$target" in
     #L_OPT="/debug"    # for debugging
     L_OPT=""           # no debug info
     LINK="link $L_OPT /nologo /subsystem:console /incremental:no /machine:I386 /out:\$@ BINMODE.OBJ"
+    LINK_CONSOLE=$LINK
     EXE=".exe"
     PRIMARY_TARGET="bochs.exe"
     # also compile niclist if networking is on
@@ -1728,25 +1893,6 @@ if test "$with_rfb" = yes -a "$cross_configure" = 0; then
   fi
 fi
 
-# since wxWindows (usually) needs pthread library, check that it was found.
-# But on win32 platforms, the pthread library is not needed.
-if test "$with_wx" = yes -a "$cross_configure" = 0; then
-  if test "$pthread_ok" = yes; then
-	GUI_LINK_OPTS="$PTHREAD_LIBS $GUI_LINK_OPTS"
-	CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
-	CXXFLAGS="$CXXFLAGS $PTHREAD_CFLAGS"
-	CC="$PTHREAD_CC"
-  else
-    case "$target" in
-	  *-pc-windows* | *-pc-winnt* | *-cygwin* | *-mingw*)
-	    # pthread not needed for win32 platform
-		;;
-	  *)
-        echo ERROR: --with-wx requires the pthread library, which could not be found.; exit 1
-    esac
-  fi
-fi
-
 # Create some subdirectories for when you run configure from some other 
 # directory.
 if test ! -d instrument; then mkdir instrument; fi
@@ -1757,6 +1903,7 @@ AC_SUBST(INSTALL_TARGET)
 AC_SUBST(INSTALL_LIST_FOR_PLATFORM)
 AC_SUBST(RFB_LIBS)
 AC_SUBST(GUI_OBJS)
+AC_SUBST(DEVICE_LINK_OPTS)
 AC_SUBST(GUI_LINK_OPTS)
 AC_SUBST(GUI_LINK_OPTS_TERM)
 AC_SUBST(GUI_LINK_OPTS_WX)
@@ -1768,6 +1915,7 @@ AC_SUBST(OFP)
 AC_SUBST(MAKELIB)
 AC_SUBST(RMCOMMAND)
 AC_SUBST(LINK)
+AC_SUBST(LINK_CONSOLE)
 AC_SUBST(EXE)
 AC_SUBST(PRIMARY_TARGET)
 AC_SUBST(COMMAND_SEPARATOR)
